version: '3.8'

services:
  email-app:
    container_name: email-app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"  # typical Rails dev port

    volumes:
      - .:/app

    environment:
      OPENAI_API_KEY: your-openai-key-here
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

    depends_on:
      - postgres

    command: sleep infinity  # or replace with: rails server -b 0.0.0.0

  postgres:
    container_name: postgres
    image: ankane/pgvector
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
