default: &default
adapter: postgresql
encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
<<: *default
database: ai_financial_advisor_development
test:
<<: *default
database: ai_financial_advisor_test
production:
<<: *default
url: <%= ENV['DATABASE_URL'] %>